services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:develop
    container_name: profilarr
    restart: unless-stopped
    ports:
      - '6869:6868'
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Etc/UTC
      # - PORT=6868
      # - HOST=0.0.0.0
      - PARSER_HOST=parser
      - PARSER_PORT=5000
    depends_on:
      parser:
        condition: service_healthy

  # Optional - only needed for CF/QP testing features
  parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:develop
    container_name: profilarr-parser
    restart: unless-stopped
    expose:
      - '5000'
