blank_issues_enabled: true

contact_links:
  - name: 💬 Support Question
    url: https://github.com/Dictionarry-Hub/profilarr/discussions/new?category=q-a
    about: Ask questions and get help from the community

  - name: 📚 Check the Docs
    url: https://dictionarry.dev
    about: Read the documentation before opening an issue
