// src/constants/languages.js
export const LANGUAGES = [
    {id: 'any', name: 'Any', isSpecial: true},
    {id: 'original', name: 'Original', isSpecial: true},
    {id: 'arabic', name: 'Arabic'},
    {id: 'bengali', name: 'Bengali'},
    {id: 'bosnian', name: 'Bosnian'},
    {id: 'bulgarian', name: 'Bulgarian'},
    {id: 'catalan', name: 'Catalan'},
    {id: 'chinese', name: 'Chinese'},
    {id: 'croatian', name: 'Croatian'},
    {id: 'czech', name: 'Czech'},
    {id: 'danish', name: 'Danish'},
    {id: 'dutch', name: 'Dutch'},
    {id: 'english', name: 'English'},
    {id: 'estonian', name: 'Estonian'},
    {id: 'finnish', name: 'Finnish'},
    {id: 'flemish', name: 'Flemish'},
    {id: 'french', name: 'French'},
    {id: 'german', name: 'German'},
    {id: 'greek', name: 'Greek'},
    {id: 'hebrew', name: 'Hebrew'},
    {id: 'hindi', name: 'Hindi'},
    {id: 'hungarian', name: 'Hungarian'},
    {id: 'icelandic', name: 'Icelandic'},
    {id: 'indonesian', name: 'Indonesian'},
    {id: 'italian', name: 'Italian'},
    {id: 'japanese', name: 'Japanese'},
    {id: 'kannada', name: 'Kannada'},
    {id: 'korean', name: 'Korean'},
    {id: 'latvian', name: 'Latvian'},
    {id: 'lithuanian', name: 'Lithuanian'},
    {id: 'macedonian', name: 'Macedonian'},
    {id: 'malayalam', name: 'Malayalam'},
    {id: 'norwegian', name: 'Norwegian'},
    {id: 'persian', name: 'Persian'},
    {id: 'polish', name: 'Polish'},
    {id: 'portuguese', name: 'Portuguese'},
    {id: 'portuguese-brazil', name: 'Portuguese (Brazil)'},
    {id: 'romanian', name: 'Romanian'},
    {id: 'russian', name: 'Russian'},
    {id: 'serbian', name: 'Serbian'},
    {id: 'slovak', name: 'Slovak'},
    {id: 'slovenian', name: 'Slovenian'},
    {id: 'spanish', name: 'Spanish'},
    {id: 'spanish-latino', name: 'Spanish (Latino)'},
    {id: 'swedish', name: 'Swedish'},
    {id: 'tamil', name: 'Tamil'},
    {id: 'telugu', name: 'Telugu'},
    {id: 'thai', name: 'Thai'},
    {id: 'turkish', name: 'Turkish'},
    {id: 'ukrainian', name: 'Ukrainian'},
    {id: 'vietnamese', name: 'Vietnamese'}
];
