name: Notify
on:
    push:
        tags:
            - 'v*'

jobs:
    notify:
        uses: Dictionarry-Hub/parrot/.github/workflows/notify.yml@main
        secrets:
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
