name: Release Notification

on:
    release:
        types: [published]

jobs:
    call-notify-release:
        uses: Dictionarry-Hub/parrot/.github/workflows/notify-release.yml@v1
        secrets:
            PARROT_URL: ${{ secrets.PARROT_URL }}
